### ISSUE TITLE
if {n[0][0].len, n[1].len} == {1}:  better turns to real set comparision.

### ISSUE THREAD

**Issue by bung87** [disruptek/balls#45]
https://github.com/disruptek/balls/blob/b44a94b093f3680db44529251db419061dcca8b6/balls.nim#L68

**Comment by bung87** [comment]
@disruptek please check this.

**Comment by disruptek** [comment]
Why not submit a PR instead?

**Comment by bung87** [comment]
I dont understand why `{int,int} == {1}`

**Comment by bung87** [comment]
so why `assert {1, 1} == {1}`

**Comment by disruptek** [comment]
The code in balls is a conditional and not an assertion.

**Comment by bung87** [comment]
`if {1, 1} == {1}` that doesn't ease my confusing

**Comment by disruptek** [comment]
How do you feel about `if {n[0][0].len, n[1].len} == {1}:` instead?

**Comment by bung87** [comment]
two numbers set compare to one number set , always false I guess?

**Comment by disruptek** [comment]
You're right; when there are two distinct values in the set, the condition is always false.  On the other hand, when there is but one distinct value in the set, the condition is always true.

**Comment by bung87** [comment]
ah, so could be duplicated value there.

**Comment by disruptek** [comment]
Feel free to open an issue if you find a bug.
