### ISSUE TITLE
How do I test for failed compilation?

### ISSUE THREAD

**Issue by moigagoo** [disruptek/balls#50]
I want to switch from testament to balls for Norm. I have tests that check for certain compilation errors: https://github.com/moigagoo/norm/blob/develop/tests/sqlite/tronocomp.Nim

How do I do such checks in balls?

**Comment by disruptek** [comment]
It's easy to use a `when compiles(someTemplate): fail"that should not have worked"` but the unittest side of balls doesn't have any knowledge of the compiler (yet) and does not run semantic analysis on test blocks or search compiler output for particular errors.  If you need that, you should stick with testament.

This isn't a terribly difficult thing to add, though the most correct implementation would probably involve importing large parts of the compiler into unittests and hooking into the error handler for sem.  I did this in my https://github.com/disruptek/dust project at some point.

Honestly, the unittesting portion of balls is not particularly special; lately, most of the development has been around the test runner (in the v4 branch), which is becoming more useful.

**Comment by moigagoo** [comment]
Thanks for the quick response! I totally forgot about the `compiles` check, thanks.
