### ISSUE TITLE
[Feature Request] Add thread and/or address sanitizers

### ISSUE THREAD

**Issue by PhilippMDoerner** [disruptek/balls#57]
Heyho, I am currently working my way through threading and making it as safe as can be to build my "microservice-multithreading" runtime on top of.

That includes adding [tsan at the moment](https://github.com/nim-lang/threading/pull/56) and in a future step asan.

 I am considering sneaking balls in the test-suite in order to get that sanitizer-coverage given how it is used a fair bit to ensure correctness and getting grinds checks essentially for free would be pretty sweet.

My question becomes: Is Asan/Tsan supported and can be used? 

I see it is already part of the [Analyzer enum](https://disruptek.github.io/balls/balls/runner.html#Analyzer) but couldn't find any further usage of it and no mention on if that means that it is automatically part of the analysis pipeline or not.

If being part of the Analyzer enum means it is part of the pipeline, then I'd suggest adding a doc comment that specifies that, potentially with links to the individual tools in the enum itself.
I'll happily make a PR to add those doc comments if desired.

**Comment by disruptek** [comment]
We fallback to asan/tsan when valgrind isn't available.  You can either `--define:ballsUseValgrind=no` when compiling the runner, or define `BALLS_VALGRIND=false` in your environment before invoking `balls` in order to force the fallback.  If these don't work, it's a bug.
